### ISSUE TITLE
Document use-case against CSS

### ISSUE THREAD

**Issue by MartinMuzatko** [LasseRafn/php-initial-avatar-generator#18]
Hello! Nice repo :)
What do you think is the main use-case to prefer static images against HTML elements with CSS applied?

**Comment by LasseRafn** [comment]
Hello! :) Thanks

Honestly? I'd probably recommend using CSS and HTML. It renders faster (no HTTP request), adds no extra server load and ensures crisp avatars.

Personally I use this mainly as a Gravatar fallback, which is hard with HTML (or so I've found)
