### ISSUE TITLE
No way to use Imagick as driver?

### ISSUE THREAD

**Issue by oh-ren** [LasseRafn/php-initial-avatar-generator#19]
Hi, from the README:

> Supported Image Libraries (from intervention/image)
  \
  GD Library (>=2.0)
  Imagick PHP extension (>=6.5.7)

But there's no way to specify to use Imagick? It uses GD by default, because that's Intervention's default.

As a solution I think it would be a good option to allow an user to inject their own `Intervention\Image\ImageManager` + be able to set one as a default (via a static method call).

Another thing: I wanted to extend your class, but that's next to impossible due to all the private members. Perhaps you can consider using `protected` visibility (wherever possible)?

Cheers ;-)

**Comment by LasseRafn** [comment]
Hi! 

Good point, I actually don't know why Imagick is stated there 🤔 .. will update! But definitively good idea with the injection and protected. I will be updating soon.

Thanks 👍

**Comment by LasseRafn** [comment]
Visibility changed to `protected` as a first thing 👍

**Comment by LasseRafn** [comment]
I will fix this.

**Comment by LasseRafn** [comment]
Tagged v3.0.0 with `->gd()` and `->imagick()` method to switch between.
