### ISSUE TITLE
Broken Return

### ISSUE THREAD

**Issue by anggaand123** [LasseRafn/php-initial-avatar-generator#20]
```
return $avatar->name('Lasse Rafn')
              ->length(2)
              ->fontSize(0.5)
              ->size(96) // 48 * 2
              ->background('#8BC34A')
              ->color('#fff')
              ->cache()
              ->generate()
              ->stream('png', 100);
```
this is output showing up [http://prntscr.com/hnahzh](url)

**Comment by LasseRafn** [comment]
Hi, sorry for the late reply. Link is not working

**Comment by anggaand123** [comment]
you should copy link manually and then paste on your browser. i tried click direct is goin to not found github .
@LasseRafn

**Comment by LasseRafn** [comment]
Hi, okay so I assume that the issue is that you're echoing the stream png part.

To fix this, you should use `->stream('data-url', 100)`

Which will return a base64 👍
