### ISSUE TITLE
Result output

### ISSUE THREAD

**Issue by emresaracoglu** [LasseRafn/php-initial-avatar-generator#25]
Hello,

```
$resim = $avatar->name('Lasse Rafn')
		->length(2)
		->fontSize(0.5)
		->size(96)// 48 * 2
		->background('#8BC34A')
		->color('#fff')
		->generate()
		->stream('png', 100);
	echo '<img src="' . $resim . '" width="48" height="48" style="border-radius: 100%" />';
```

Result:

> <img src="�PNG  IHDR00W���IDATh��=��@����� i�"),�X����R��"���R�2��"������D삤�s�]؏qd.�S��y9O ��@��H�x!�!�!�!�!�!�!���\�A��P����� ��y��fh�ۈD"L����K�C���p�\�,CQ�R)��i���l6��rɜOa��DD��z���Q�Z�kOUU�L&DD���C����� �GT*\�Wh��d2ɔ��#�����*S�.�( ��<��\���8n�V�S��$IB,C�^�t:�$I�,���9�w���n����;z��l68�N��3�$IB.���px9��s��m""��/�}��m�|>�X,�0�������f� ��z�e�9�[�����4 �e1�p��i��x��j1Ob�.������?���.�A���b��h�Z��N��r��t-L��}��F��j4( (�J0��>u��_�o�o�o�o�o�o���'#+X���{IEND�B`�"/>

What cloud be reason for this?

Thank you?

**Comment by LasseRafn** [comment]
Hi! You can use `stream(‘data-url’)` to output to base64, which will work.

The stream(‘png’, 100) is used when you return it in a http response (for example an endpoint that returns user avatar)

Hope this helps!

**Comment by emresaracoglu** [comment]
All right, I did it. Thank you again.

@LasseRafn

**Comment by LasseRafn** [comment]
Glad to hear! 👍  No problem

**Comment by SoftCreatR** [comment]
Alternatively, add an appropiate header:

`header("Content-type: image/png");`
