### ISSUE TITLE
Saving the generated image

### ISSUE THREAD

**Issue by olubunmi708** [LasseRafn/php-initial-avatar-generator#27]
Kudos for the hard-work. Please how can i save the image file in a folder after generation?
Thanks.

**Comment by LasseRafn** [comment]
Hi! Thanks so much 👍 

Okay, to save, you can use this:

```
->save('png'); 

// optionally specifying the percentage quality after like so: ->save('jpg', 100) 
```

**Comment by LasseRafn** [comment]
We use Intervention/Image, so heres docs: http://image.intervention.io/api/save

you should be able to use the same methods as well 👍
