### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by gildastema** [LasseRafn/php-initial-avatar-generator#39]
Beacause 
 Problem 1
    - Installation request for rackbeat/laravel-ui-avatars ^0.7.0 -> satisfiable by rackbeat/laravel-ui-avatars[0.7].
    - Conclusion: remove lasserafn/php-initial-avatar-generator 4.0.2
    - Conclusion: don't install lasserafn/php-initial-avatar-generator 4.0.2
    - rackbeat/laravel-ui-avatars 0.7 requires lasserafn/php-initial-avatar-generator ^3.0 -> satisfiable by lasserafn/php-initial-avatar-generator[3.0.0, 3.0.1, 3.0.2, 3.0.3].
    - Can only install one of: lasserafn/php-initial-avatar-generator[3.0.0, 4.0.2].
    - Can only install one of: lasserafn/php-initial-avatar-generator[3.0.1, 4.0.2].
    - Can only install one of: lasserafn/php-initial-avatar-generator[3.0.2, 4.0.2].
    - Can only install one of: lasserafn/php-initial-avatar-generator[3.0.3, 4.0.2].
    - Installation request for lasserafn/php-initial-avatar-generator (locked at 4.0.2) -> satisfiable by lasserafn/php-initial-avatar-generator[4.0.2].

**Comment by LasseRafn** [comment]
Hi! thanks for bringing this to my attention. I've pushed a new release of `rackbeat/laravel-ui-avatars` (0.8) which resolves this! Sorry
