### ISSUE TITLE
UTF-8 characters?

### ISSUE THREAD

**Issue by axlyody** [LasseRafn/php-initial-avatar-generator#4]
Does it supports with utf8 like japanese name or something similar?

**Comment by LasseRafn** [comment]
Hi! 

Well, I've tested it with some letters that require UTF8, and it uses `mb_` methods to also ensure support — However I have not yet tested Japanese letters, I think the only problem would be the font. It uses Open Sans as default, and I don't know if it supports Japanese letters.

You can however change the font as per your needs. Maybe I'll find an alternative font to use as default.

I'll test it later 👍

**Comment by LasseRafn** [comment]
Okay, so Open Sans does **NOT** support Japanese letters, but I found a font that does, and included it in the next release.

Using the following code should give you an avatar that works as intended:

```php
<?php

require_once 'vendor/autoload.php';

$avatar = new LasseRafn\InitialAvatarGenerator\InitialAvatar();

echo $avatar->font('/fonts/NotoSans-Medium.otf')
            ->generate('こんにちは')
            ->stream('data-url');
```

This was my result: 
![demo](https://cloud.githubusercontent.com/assets/2689341/24540116/0dc3daf4-15f2-11e7-8713-5cf61fa666d0.png)

You may want to reduce the font size using `->fontSize(0.4)` (default is 0.5, which is 50% of the image size)
