### ISSUE TITLE
PHP 8 Support 

### ISSUE THREAD

**Issue by pyatnitsev** [LasseRafn/php-initial-avatar-generator#53]
main package lasserafn/php-initial-avatar-generator supports php8 as well, but 
lasserafn/php-initials required 7.1+, it would be nice to support PHP 8.0 completely.

**Comment by LasseRafn** [comment]
Done 👍

**Comment by pyatnitsev** [comment]
Sorry, but https://packagist.org/packages/lasserafn/php-string-script-language is dependency too. It's supports only php 7.x

**Comment by pyatnitsev** [comment]
@LasseRafn https://github.com/LasseRafn/php-string-script-language/pull/2

**Comment by LasseRafn** [comment]
🤦🏻‍♂️ forgot! Thanks, merged and making release now

**Comment by pyatnitsev** [comment]
I just tried to update my dependencies with php 8 reqirement and got follow:

```
- lasserafn/php-string-script-language 0.1 requires php ^5.6|^7.0|^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - lasserafn/php-initial-avatar-generator 4.2.0 requires lasserafn/php-string-script-language ^0.1.0 -> satisfiable by lasserafn/php-string-script-language[0.1].
    - Root composer.json requires lasserafn/php-initial-avatar-generator ^4.2 -> satisfiable by lasserafn/php-initial-avatar-generator[4.2.0].
```

**Comment by pyatnitsev** [comment]
"lasserafn/php-string-script-language": "^0.1.0", required 0.1+ version like 0.1.0 or 0.1.2 or more, 
You're push version to 0.3.0 and it's can't be used with this package. It breakes PHP8 support

**Comment by LasseRafn** [comment]
Ah yes, try 4.2.1 now — that requires v0.3 👍

**Comment by pyatnitsev** [comment]
https://github.com/LasseRafn/php-initial-avatar-generator/pull/54 - PR to bump php-string-script-language version.

**Comment by pyatnitsev** [comment]
Ok, thanks!

**Comment by pyatnitsev** [comment]
Thank you for your time. Now this package support PHP 8

**Comment by LasseRafn** [comment]
Thanks 🎉
