### ISSUE TITLE
Deprecation Notice: Dynamic property creation in InitialAvatar.php with php 8.2

### ISSUE THREAD

**Issue by h3llr4iser** [LasseRafn/php-initial-avatar-generator#60]
Hello,

I've been using your PHP Initial Avatar Generator library and it has been very helpful. However, I've encountered a deprecation notice  with a recent version of PHP. Here's the notice:

Deprecated: Creation of dynamic property LasseRafn\InitialAvatarGenerator\InitialAvatar::$translato is deprecated in /srv/api/vendor/lasserafn/php-initial-avatar-generator/src/InitialAvatar.php on line 571

Would it be possible to update the code to avoid the use of dynamic properties and thus resolve this deprecation notice? 

Thanks for your attention to this matter. I appreciate your work on this library and look forward to your response.

**Comment by LasseRafn** [comment]
Yes!

**Comment by LasseRafn** [comment]
Ah it was fixed already, sorry for not updating!
