### ISSUE TITLE
Compile Error: Cannot use lexical variable $font as a parameter name in InitialAvatar.php

### ISSUE THREAD

**Issue by tomStory9** [LasseRafn/php-initial-avatar-generator#63]
---

**Title**: Compile Error: Cannot use lexical variable `$font` as a parameter name in `InitialAvatar.php`

**Description**:
I encountered a `Compile Error` in `InitialAvatar.php` due to the use of `$font` as a parameter name in a function. In PHP, lexical variables cannot be reused as parameter names within closures. This results in the following error:

```
[critical] Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Cannot use lexical variable $font as a parameter name" at InitialAvatar.php line 28
```

**Steps to Reproduce**:
1. Use the `InitialAvatar` class in a Symfony project or any PHP project that utilizes dependency injection for configuration.
2. Attempt to generate an avatar, which causes the code at line 28 in `InitialAvatar.php` to execute.

**Expected Behavior**:
The avatar should be generated without triggering a compile error.

**Proposed Solution**:
Rename the `$font` parameter within the affected function or closure to avoid conflicts with lexical scoping. This should resolve the compile error.

**Environment**:
- PHP Version: [8.2.9]
- `InitialAvatarGenerator` Version: v0.1.7

Thank you for your assistance! Please let me know if you need further details to resolve this issue.

**Comment by LasseRafn** [comment]
Thanks for reporting and providing a fix in #64  😄
